-- 初期データが存在しない場合のみ投入
INSERT INTO TODO (TITLE, DESCRIPTION, COMPLETED, CREATED_AT)
SELECT 'Spring Bootの学習', 'Spring Bootアプリケーションの基本を理解する', FALSE, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM TODO);

INSERT INTO TODO (TITLE, DESCRIPTION, COMPLETED, CREATED_AT)
SELECT 'ToDoリストの実装', 'REST APIとフロントエンドを実装する', FALSE, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM TODO WHERE TITLE = 'ToDoリストの実装');

INSERT INTO TODO (TITLE, DESCRIPTION, COMPLETED, CREATED_AT)
SELECT 'プロジェクトのテスト', '作成したアプリケーションの動作確認', FALSE, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM TODO WHERE TITLE = 'プロジェクトのテスト');
