package com.example.demo;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * ProjectServiceの統合テストクラス
 *
 * @see ProjectService
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
@DisplayName("ProjectService 統合テスト")
class ProjectServiceTest {

    @Autowired
    private ProjectService projectService;

    @Autowired
    private ProjectMapper projectMapper;

    @Autowired
    private TodoMapper todoMapper;

    @BeforeEach
    void setUp() {
        // テストデータをクリア
        todoMapper.deleteAll();
        // PROJECTは外部キー制約があるため、TODOを先に削除
        List<Project> projects = projectMapper.selectAll();
        for (Project p : projects) {
            projectMapper.deleteById(p.getId());
        }
    }

    // ========================================
    // getAllProjects() テスト
    // ========================================
    @Nested
    @DisplayName("getAllProjects()")
    class GetAllProjectsTest {

        @Test
        @DisplayName("TC-PS-001: 登録済み案件が作成日時降順で取得できる")
        void getAllProjects_WhenExists_ReturnsProjectsSortedByCreatedAtDesc() {
            Project project1 = new Project("案件A", "説明A");
            projectMapper.insert(project1);
            Project project2 = new Project("案件B", "説明B");
            projectMapper.insert(project2);

            List<Project> projects = projectService.getAllProjects();

            assertThat(projects).hasSize(2);
            // 降順であることを確認（新しいものが先）
            assertThat(projects.get(0).getCreatedAt())
                .isAfterOrEqualTo(projects.get(1).getCreatedAt());
        }

        @Test
        @DisplayName("TC-PS-002: 案件が0件の場合、空リストが返却される")
        void getAllProjects_WhenEmpty_ReturnsEmptyList() {
            List<Project> projects = projectService.getAllProjects();

            assertThat(projects).isEmpty();
        }
    }

    // ========================================
    // getProjectById() テスト
    // ========================================
    @Nested
    @DisplayName("getProjectById()")
    class GetProjectByIdTest {

        @Test
        @DisplayName("TC-PS-003: 存在するIDで案件が取得できる")
        void getProjectById_WhenExists_ReturnsProject() {
            Project project = new Project("テスト案件", "説明");
            projectMapper.insert(project);

            Project result = projectService.getProjectById(project.getId());

            assertThat(result).isNotNull();
            assertThat(result.getId()).isEqualTo(project.getId());
            assertThat(result.getName()).isEqualTo("テスト案件");
        }

        @Test
        @DisplayName("TC-PS-004: 存在しないIDでnullが返却される")
        void getProjectById_WhenNotExists_ReturnsNull() {
            Project result = projectService.getProjectById(999L);

            assertThat(result).isNull();
        }
    }

    // ========================================
    // createProject() テスト
    // ========================================
    @Nested
    @DisplayName("createProject()")
    class CreateProjectTest {

        @Test
        @DisplayName("TC-PS-005: 正常な案件作成でIDが付与される")
        void createProject_WhenValid_CreatesWithAutoGeneratedId() {
            Project project = new Project("新規案件", "説明");

            Project created = projectService.createProject(project);

            assertThat(created.getId()).isNotNull();
            assertThat(created.getName()).isEqualTo("新規案件");
            assertThat(created.getDescription()).isEqualTo("説明");
            assertThat(created.getCreatedAt()).isNotNull();
        }

        @Test
        @DisplayName("TC-PS-006: descriptionがnullでも作成できる")
        void createProject_WhenDescriptionNull_CreatesSuccessfully() {
            Project project = new Project("案件名", null);

            Project created = projectService.createProject(project);

            assertThat(created.getId()).isNotNull();
            assertThat(created.getName()).isEqualTo("案件名");
            assertThat(created.getDescription()).isNull();
        }
    }

    // ========================================
    // updateProject() テスト
    // ========================================
    @Nested
    @DisplayName("updateProject()")
    class UpdateProjectTest {

        @Test
        @DisplayName("TC-PS-007: 存在する案件を正常に更新できる")
        void updateProject_WhenExists_UpdatesSuccessfully() {
            Project project = new Project("元の名前", "元の説明");
            projectMapper.insert(project);

            Project updatedData = new Project("更新後の名前", "更新後の説明");
            Project result = projectService.updateProject(project.getId(), updatedData);

            assertThat(result).isNotNull();
            assertThat(result.getName()).isEqualTo("更新後の名前");
            assertThat(result.getDescription()).isEqualTo("更新後の説明");
        }

        @Test
        @DisplayName("TC-PS-008: 存在しないIDでnullが返却される")
        void updateProject_WhenNotExists_ReturnsNull() {
            Project updatedData = new Project("更新", "説明");

            Project result = projectService.updateProject(999L, updatedData);

            assertThat(result).isNull();
        }
    }

    // ========================================
    // deleteProject() テスト
    // ========================================
    @Nested
    @DisplayName("deleteProject()")
    class DeleteProjectTest {

        @Test
        @DisplayName("TC-PS-009: 配下チケットなしの案件が削除できる")
        void deleteProject_WhenNoTodos_DeletesSuccessfully() {
            Project project = new Project("削除案件", "説明");
            projectMapper.insert(project);
            int originalCount = projectMapper.selectAll().size();

            Project deleted = projectService.deleteProject(project.getId());

            assertThat(deleted).isNotNull();
            assertThat(deleted.getId()).isEqualTo(project.getId());
            assertThat(projectMapper.selectAll()).hasSize(originalCount - 1);
        }

        @Test
        @DisplayName("TC-PS-010: 案件削除時に配下チケットも削除される（カスケード削除）")
        void deleteProject_WhenHasTodos_DeletesTodosAsWell() {
            // 案件を作成
            Project project = new Project("カスケード案件", "説明");
            projectMapper.insert(project);

            // 配下にチケットを3件作成
            for (int i = 1; i <= 3; i++) {
                Todo todo = new Todo("タスク" + i, "説明" + i);
                todo.setProjectId(project.getId());
                todoMapper.insert(todo);
            }
            assertThat(todoMapper.countByProjectId(project.getId())).isEqualTo(3);

            // 案件を削除
            Project deleted = projectService.deleteProject(project.getId());

            assertThat(deleted).isNotNull();
            // 案件が削除されている
            assertThat(projectMapper.selectById(project.getId())).isNull();
            // 配下チケットも削除されている
            assertThat(todoMapper.countByProjectId(project.getId())).isZero();
        }

        @Test
        @DisplayName("TC-PS-011: 存在しないIDでnullが返却される")
        void deleteProject_WhenNotExists_ReturnsNull() {
            Project result = projectService.deleteProject(999L);

            assertThat(result).isNull();
        }
    }

    // ========================================
    // getProjectStats() テスト
    // ========================================
    @Nested
    @DisplayName("getProjectStats()")
    class GetProjectStatsTest {

        @Test
        @DisplayName("TC-PS-012: 全て未完了の場合の統計が正しい")
        void getProjectStats_WhenAllPending_ReturnsCorrectStats() {
            Project project = new Project("統計案件", "説明");
            projectMapper.insert(project);

            for (int i = 1; i <= 3; i++) {
                Todo todo = new Todo("タスク" + i, "説明");
                todo.setProjectId(project.getId());
                todoMapper.insert(todo);
            }

            Map<String, Integer> stats = projectService.getProjectStats(project.getId());

            assertThat(stats.get("total")).isEqualTo(3);
            assertThat(stats.get("completed")).isEqualTo(0);
            assertThat(stats.get("pending")).isEqualTo(3);
            assertThat(stats.get("progressRate")).isEqualTo(0);
        }

        @Test
        @DisplayName("TC-PS-013: 一部完了の場合の統計・進捗率が正しい")
        void getProjectStats_WhenPartialComplete_ReturnsCorrectStats() {
            Project project = new Project("統計案件", "説明");
            projectMapper.insert(project);

            // 10件のチケットを作成し、3件を完了にする
            for (int i = 1; i <= 10; i++) {
                Todo todo = new Todo("タスク" + i, "説明");
                todo.setProjectId(project.getId());
                todo.setCompleted(i <= 3); // 1〜3は完了
                todoMapper.insert(todo);
            }

            Map<String, Integer> stats = projectService.getProjectStats(project.getId());

            assertThat(stats.get("total")).isEqualTo(10);
            assertThat(stats.get("completed")).isEqualTo(3);
            assertThat(stats.get("pending")).isEqualTo(7);
            assertThat(stats.get("progressRate")).isEqualTo(30);
        }

        @Test
        @DisplayName("TC-PS-014: 全て完了の場合の進捗率が100%")
        void getProjectStats_WhenAllComplete_ReturnsProgressRate100() {
            Project project = new Project("統計案件", "説明");
            projectMapper.insert(project);

            for (int i = 1; i <= 5; i++) {
                Todo todo = new Todo("タスク" + i, "説明");
                todo.setProjectId(project.getId());
                todo.setCompleted(true);
                todoMapper.insert(todo);
            }

            Map<String, Integer> stats = projectService.getProjectStats(project.getId());

            assertThat(stats.get("total")).isEqualTo(5);
            assertThat(stats.get("completed")).isEqualTo(5);
            assertThat(stats.get("pending")).isEqualTo(0);
            assertThat(stats.get("progressRate")).isEqualTo(100);
        }

        @Test
        @DisplayName("TC-PS-015: チケット0件の場合の進捗率が0%")
        void getProjectStats_WhenNoTodos_ReturnsProgressRate0() {
            Project project = new Project("空の案件", "説明");
            projectMapper.insert(project);

            Map<String, Integer> stats = projectService.getProjectStats(project.getId());

            assertThat(stats.get("total")).isEqualTo(0);
            assertThat(stats.get("completed")).isEqualTo(0);
            assertThat(stats.get("pending")).isEqualTo(0);
            assertThat(stats.get("progressRate")).isEqualTo(0);
        }

        @Test
        @DisplayName("TC-PS-016: 進捗率が小数点以下切り捨てになる")
        void getProjectStats_ProgressRateIsTruncated() {
            Project project = new Project("統計案件", "説明");
            projectMapper.insert(project);

            // 3件中1件完了 = 33.33...%
            for (int i = 1; i <= 3; i++) {
                Todo todo = new Todo("タスク" + i, "説明");
                todo.setProjectId(project.getId());
                todo.setCompleted(i == 1);
                todoMapper.insert(todo);
            }

            Map<String, Integer> stats = projectService.getProjectStats(project.getId());

            assertThat(stats.get("progressRate")).isEqualTo(33); // 切り捨て
        }
    }
}
