package com.example.demo;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.mybatis.spring.boot.test.autoconfigure.MybatisTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * TodoMapperの単体テストクラス
 *
 * @see TodoMapper
 */
@MybatisTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ActiveProfiles("test")
@DisplayName("TodoMapper 単体テスト")
class TodoMapperTest {

    @Autowired
    private TodoMapper todoMapper;

    @BeforeEach
    void setUp() {
        // テストデータをクリアして初期データを投入
        todoMapper.deleteAll();

        Todo todo1 = new Todo("Spring Bootの学習", "説明1");
        todoMapper.insert(todo1);

        Todo todo2 = new Todo("ToDoリストの実装", "説明2");
        todoMapper.insert(todo2);

        Todo todo3 = new Todo("プロジェクトのテスト", "説明3");
        todoMapper.insert(todo3);
    }

    // ========================================
    // selectAll() テスト
    // ========================================
    @Nested
    @DisplayName("selectAll()")
    class SelectAllTest {

        @Test
        @DisplayName("M-001: 全件取得で作成日時順にリストが取得できる")
        void selectAll_ReturnsAllTodosSortedByCreatedAt() {
            List<Todo> todos = todoMapper.selectAll();

            assertThat(todos).hasSize(3);
            // 作成日時でソートされていることを確認
            for (int i = 0; i < todos.size() - 1; i++) {
                assertThat(todos.get(i).getCreatedAt())
                    .isBeforeOrEqualTo(todos.get(i + 1).getCreatedAt());
            }
        }
    }

    // ========================================
    // selectById() テスト
    // ========================================
    @Nested
    @DisplayName("selectById()")
    class SelectByIdTest {

        @Test
        @DisplayName("M-002: 存在するID指定で該当Todoオブジェクトが取得できる")
        void selectById_WhenExists_ReturnsTodo() {
            List<Todo> allTodos = todoMapper.selectAll();
            Long existingId = allTodos.get(0).getId();

            Todo todo = todoMapper.selectById(existingId);

            assertThat(todo).isNotNull();
            assertThat(todo.getId()).isEqualTo(existingId);
            assertThat(todo.getTitle()).isEqualTo("Spring Bootの学習");
        }

        @Test
        @DisplayName("M-003: 存在しないID指定でnullが返却される")
        void selectById_WhenNotExists_ReturnsNull() {
            Todo todo = todoMapper.selectById(999L);

            assertThat(todo).isNull();
        }
    }

    // ========================================
    // selectByCompleted() テスト
    // ========================================
    @Nested
    @DisplayName("selectByCompleted()")
    class SelectByCompletedTest {

        @Test
        @DisplayName("M-004: completed=trueで完了済みのみ取得できる")
        void selectByCompleted_WhenTrue_ReturnsCompletedOnly() {
            // 1件を完了にする
            List<Todo> allTodos = todoMapper.selectAll();
            Todo todo = allTodos.get(0);
            todo.setCompleted(true);
            todoMapper.update(todo);

            List<Todo> completedTodos = todoMapper.selectByCompleted(true);

            assertThat(completedTodos).hasSize(1);
            assertThat(completedTodos).allMatch(Todo::isCompleted);
        }

        @Test
        @DisplayName("M-005: completed=falseで未完了のみ取得できる")
        void selectByCompleted_WhenFalse_ReturnsPendingOnly() {
            // 1件を完了にする
            List<Todo> allTodos = todoMapper.selectAll();
            Todo todo = allTodos.get(0);
            todo.setCompleted(true);
            todoMapper.update(todo);

            List<Todo> pendingTodos = todoMapper.selectByCompleted(false);

            assertThat(pendingTodos).hasSize(2);
            assertThat(pendingTodos).allMatch(t -> !t.isCompleted());
        }
    }

    // ========================================
    // insert() テスト
    // ========================================
    @Nested
    @DisplayName("insert()")
    class InsertTest {

        @Test
        @DisplayName("M-006: 正常なTodo挿入でIDが自動採番され返却される")
        void insert_WhenValid_AssignsAutoGeneratedId() {
            Todo newTodo = new Todo("新しいタスク", "新しい説明");

            todoMapper.insert(newTodo);

            assertThat(newTodo.getId()).isNotNull();

            // DBから取得して確認
            Todo savedTodo = todoMapper.selectById(newTodo.getId());
            assertThat(savedTodo).isNotNull();
            assertThat(savedTodo.getTitle()).isEqualTo("新しいタスク");
            assertThat(savedTodo.getDescription()).isEqualTo("新しい説明");
            assertThat(savedTodo.isCompleted()).isFalse();
        }

        @Test
        @DisplayName("M-007: description=nullで正常に挿入できる")
        void insert_WhenDescriptionNull_InsertsSuccessfully() {
            Todo newTodo = new Todo("タスク", null);

            todoMapper.insert(newTodo);

            assertThat(newTodo.getId()).isNotNull();
            Todo savedTodo = todoMapper.selectById(newTodo.getId());
            assertThat(savedTodo.getDescription()).isNull();
        }
    }

    // ========================================
    // update() テスト
    // ========================================
    @Nested
    @DisplayName("update()")
    class UpdateTest {

        @Test
        @DisplayName("M-008: 既存Todoの更新が正常に行われる")
        void update_WhenExists_UpdatesSuccessfully() {
            List<Todo> allTodos = todoMapper.selectAll();
            Todo todo = allTodos.get(0);
            Long id = todo.getId();

            todo.setTitle("更新タイトル");
            todo.setDescription("更新説明");
            todo.setCompleted(true);

            todoMapper.update(todo);

            Todo updatedTodo = todoMapper.selectById(id);
            assertThat(updatedTodo.getTitle()).isEqualTo("更新タイトル");
            assertThat(updatedTodo.getDescription()).isEqualTo("更新説明");
            assertThat(updatedTodo.isCompleted()).isTrue();
        }

        @Test
        @DisplayName("M-009: 存在しないIDで更新しても影響なし")
        void update_WhenNotExists_NoEffect() {
            Todo nonExistentTodo = new Todo("存在しない", "説明");
            nonExistentTodo.setId(999L);

            // 例外が発生しないことを確認
            todoMapper.update(nonExistentTodo);

            // 件数に変化がないことを確認
            assertThat(todoMapper.count()).isEqualTo(3);
        }
    }

    // ========================================
    // deleteById() テスト
    // ========================================
    @Nested
    @DisplayName("deleteById()")
    class DeleteByIdTest {

        @Test
        @DisplayName("M-010: 既存Todoの削除が正常に行われる")
        void deleteById_WhenExists_DeletesSuccessfully() {
            List<Todo> allTodos = todoMapper.selectAll();
            Long existingId = allTodos.get(0).getId();
            int originalCount = todoMapper.count();

            todoMapper.deleteById(existingId);

            assertThat(todoMapper.count()).isEqualTo(originalCount - 1);
            assertThat(todoMapper.selectById(existingId)).isNull();
        }

        @Test
        @DisplayName("M-011: 存在しないIDで削除しても影響なし")
        void deleteById_WhenNotExists_NoEffect() {
            int originalCount = todoMapper.count();

            todoMapper.deleteById(999L);

            assertThat(todoMapper.count()).isEqualTo(originalCount);
        }
    }

    // ========================================
    // deleteAll() テスト
    // ========================================
    @Nested
    @DisplayName("deleteAll()")
    class DeleteAllTest {

        @Test
        @DisplayName("M-012: 全件削除で全レコードが削除される")
        void deleteAll_DeletesAllRecords() {
            assertThat(todoMapper.count()).isEqualTo(3);

            todoMapper.deleteAll();

            assertThat(todoMapper.count()).isZero();
            assertThat(todoMapper.selectAll()).isEmpty();
        }
    }

    // ========================================
    // count() テスト
    // ========================================
    @Nested
    @DisplayName("count()")
    class CountTest {

        @Test
        @DisplayName("M-013: 件数取得で正確な件数が返却される")
        void count_ReturnsCorrectCount() {
            assertThat(todoMapper.count()).isEqualTo(3);

            todoMapper.insert(new Todo("追加タスク", "説明"));

            assertThat(todoMapper.count()).isEqualTo(4);
        }
    }

    // ========================================
    // countByCompleted() テスト
    // ========================================
    @Nested
    @DisplayName("countByCompleted()")
    class CountByCompletedTest {

        @Test
        @DisplayName("M-014: 完了件数取得で完了済みの件数が返却される")
        void countByCompleted_WhenTrue_ReturnsCompletedCount() {
            // 初期状態では完了0件
            assertThat(todoMapper.countByCompleted(true)).isZero();

            // 2件を完了にする
            List<Todo> allTodos = todoMapper.selectAll();
            Todo todo1 = allTodos.get(0);
            todo1.setCompleted(true);
            todoMapper.update(todo1);

            Todo todo2 = allTodos.get(1);
            todo2.setCompleted(true);
            todoMapper.update(todo2);

            assertThat(todoMapper.countByCompleted(true)).isEqualTo(2);
        }

        @Test
        @DisplayName("M-015: 未完了件数取得で未完了の件数が返却される")
        void countByCompleted_WhenFalse_ReturnsPendingCount() {
            // 初期状態では未完了3件
            assertThat(todoMapper.countByCompleted(false)).isEqualTo(3);

            // 1件を完了にする
            List<Todo> allTodos = todoMapper.selectAll();
            Todo todo = allTodos.get(0);
            todo.setCompleted(true);
            todoMapper.update(todo);

            assertThat(todoMapper.countByCompleted(false)).isEqualTo(2);
        }
    }
}
