package com.example.demo;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.mybatis.spring.boot.test.autoconfigure.MybatisTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * UserMapperの単体テストクラス
 * テスト仕様書: TC-M01 ~ TC-M07
 *
 * @see UserMapper
 */
@MybatisTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ActiveProfiles("test")
@DisplayName("UserMapper 単体テスト")
class UserMapperTest {

    @Autowired
    private UserMapper userMapper;

    @BeforeEach
    void setUp() {
        // テストデータをクリア
        // Note: 外部キー制約があるため、まずToDoを削除する必要がある場合がある
        // ここではUserMapperのみテストするため、直接削除
    }

    // ========================================
    // selectAll() テスト
    // ========================================
    @Nested
    @DisplayName("selectAll()")
    class SelectAllTest {

        @Test
        @DisplayName("TC-M01: データありで全ユーザーが作成日時昇順で取得できる")
        void selectAll_WhenDataExists_ReturnsAllUsersSortedByCreatedAt() {
            // 初期データ（data.sqlで投入済み）を利用
            List<User> users = userMapper.selectAll();

            assertThat(users).hasSizeGreaterThanOrEqualTo(3);
            // 作成日時でソートされていることを確認
            for (int i = 0; i < users.size() - 1; i++) {
                assertThat(users.get(i).getCreatedAt())
                    .isBeforeOrEqualTo(users.get(i + 1).getCreatedAt());
            }
        }

        @Test
        @DisplayName("TC-M02: データなしで空リストが返却される")
        void selectAll_WhenNoData_ReturnsEmptyList() {
            // 全ユーザーを削除
            List<User> allUsers = userMapper.selectAll();
            for (User user : allUsers) {
                userMapper.deleteById(user.getId());
            }

            List<User> result = userMapper.selectAll();

            assertThat(result).isEmpty();
        }
    }

    // ========================================
    // selectById() テスト
    // ========================================
    @Nested
    @DisplayName("selectById()")
    class SelectByIdTest {

        @Test
        @DisplayName("TC-M03: 存在するID指定で該当ユーザーが取得できる")
        void selectById_WhenExists_ReturnsUser() {
            List<User> allUsers = userMapper.selectAll();
            assertThat(allUsers).isNotEmpty();
            Long existingId = allUsers.get(0).getId();

            User user = userMapper.selectById(existingId);

            assertThat(user).isNotNull();
            assertThat(user.getId()).isEqualTo(existingId);
        }

        @Test
        @DisplayName("TC-M04: 存在しないID指定でnullが返却される")
        void selectById_WhenNotExists_ReturnsNull() {
            User user = userMapper.selectById(999L);

            assertThat(user).isNull();
        }
    }

    // ========================================
    // selectByName() テスト
    // ========================================
    @Nested
    @DisplayName("selectByName()")
    class SelectByNameTest {

        @Test
        @DisplayName("TC-M05: 存在する名前指定で該当ユーザーが取得できる")
        void selectByName_WhenExists_ReturnsUser() {
            // 初期データの「山田太郎」を検索
            User user = userMapper.selectByName("山田太郎");

            assertThat(user).isNotNull();
            assertThat(user.getName()).isEqualTo("山田太郎");
        }

        @Test
        @DisplayName("TC-M05b: 存在しない名前指定でnullが返却される")
        void selectByName_WhenNotExists_ReturnsNull() {
            User user = userMapper.selectByName("存在しないユーザー");

            assertThat(user).isNull();
        }
    }

    // ========================================
    // insert() テスト
    // ========================================
    @Nested
    @DisplayName("insert()")
    class InsertTest {

        @Test
        @DisplayName("TC-M06: 正常なユーザー挿入でIDが自動採番される")
        void insert_WhenValid_AssignsAutoGeneratedId() {
            User newUser = new User();
            newUser.setName("テストユーザー");

            userMapper.insert(newUser);

            assertThat(newUser.getId()).isNotNull();

            // DBから取得して確認
            User savedUser = userMapper.selectById(newUser.getId());
            assertThat(savedUser).isNotNull();
            assertThat(savedUser.getName()).isEqualTo("テストユーザー");
            assertThat(savedUser.getCreatedAt()).isNotNull();
        }
    }

    // ========================================
    // deleteById() テスト
    // ========================================
    @Nested
    @DisplayName("deleteById()")
    class DeleteByIdTest {

        @Test
        @DisplayName("TC-M07: 既存ユーザーの削除が正常に行われる")
        void deleteById_WhenExists_DeletesSuccessfully() {
            // 新規ユーザーを追加して削除テスト
            User newUser = new User();
            newUser.setName("削除テストユーザー");
            userMapper.insert(newUser);
            Long userId = newUser.getId();

            userMapper.deleteById(userId);

            assertThat(userMapper.selectById(userId)).isNull();
        }

        @Test
        @DisplayName("TC-M07b: 存在しないIDで削除しても影響なし")
        void deleteById_WhenNotExists_NoEffect() {
            int originalCount = userMapper.count();

            userMapper.deleteById(999L);

            assertThat(userMapper.count()).isEqualTo(originalCount);
        }
    }

    // ========================================
    // count() テスト
    // ========================================
    @Nested
    @DisplayName("count()")
    class CountTest {

        @Test
        @DisplayName("TC-M07c: 件数取得で正確な件数が返却される")
        void count_ReturnsCorrectCount() {
            int initialCount = userMapper.count();

            User newUser = new User();
            newUser.setName("カウントテストユーザー");
            userMapper.insert(newUser);

            assertThat(userMapper.count()).isEqualTo(initialCount + 1);
        }
    }
}
