-- ユーザー初期データ
INSERT INTO APP_USER (NAME)
SELECT '山田太郎'
WHERE NOT EXISTS (SELECT 1 FROM APP_USER WHERE NAME = '山田太郎');

INSERT INTO APP_USER (NAME)
SELECT '鈴木花子'
WHERE NOT EXISTS (SELECT 1 FROM APP_USER WHERE NAME = '鈴木花子');

INSERT INTO APP_USER (NAME)
SELECT '佐藤一郎'
WHERE NOT EXISTS (SELECT 1 FROM APP_USER WHERE NAME = '佐藤一郎');

-- ToDo初期データ
INSERT INTO TODO (TITLE, DESCRIPTION, COMPLETED, CREATED_AT)
SELECT 'Spring Bootの学習', 'Spring Bootアプリケーションの基本を理解する', FALSE, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM TODO);

INSERT INTO TODO (TITLE, DESCRIPTION, COMPLETED, CREATED_AT)
SELECT 'ToDoリストの実装', 'REST APIとフロントエンドを実装する', FALSE, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM TODO WHERE TITLE = 'ToDoリストの実装');

INSERT INTO TODO (TITLE, DESCRIPTION, COMPLETED, CREATED_AT)
SELECT 'プロジェクトのテスト', '作成したアプリケーションの動作確認', FALSE, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM TODO WHERE TITLE = 'プロジェクトのテスト');
