-- APP_USERテーブル作成（担当者マスタ）
-- IF NOT EXISTS: テーブルが存在しない場合のみ作成（既存データを保持）
CREATE TABLE IF NOT EXISTS APP_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_APP_USER_NAME UNIQUE (NAME)
);

-- PROJECTテーブル作成
CREATE TABLE IF NOT EXISTS PROJECT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- TODOテーブル作成
CREATE TABLE IF NOT EXISTS TODO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    COMPLETED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROJECT_ID BIGINT,
    START_DATE DATE,
    DUE_DATE DATE,
    ASSIGNEE_ID BIGINT,
    CONSTRAINT FK_TODO_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID) ON DELETE CASCADE,
    CONSTRAINT FK_TODO_USER FOREIGN KEY (ASSIGNEE_ID) REFERENCES APP_USER(ID) ON DELETE SET NULL
);

-- インデックス作成
CREATE INDEX IF NOT EXISTS IDX_TODO_PROJECT_ID ON TODO (PROJECT_ID);
CREATE INDEX IF NOT EXISTS IDX_TODO_ASSIGNEE_ID ON TODO (ASSIGNEE_ID);
